In [1]:
import os, csv
import pandas as pd
import numpy as np

In [2]:
# Number of Mortality.
file_path = os.path.join("datas", "new_mortality", "original_mortality_data.csv")

df = pd.read_csv(file_path)

In [3]:
# Fill NaN with corresponding city
df["Geography"] = df["Geography"].ffill(axis=0)

# Only include All ages for convience.
df = df.loc[df["Age group"]== "All ages"]
# reset index and drop previous one.
df = df.reset_index(drop=True)

In [4]:
# get rid of commas and converting types to integer.
# take out only columns I want to convert
cols = df.columns.drop(["Geography", "Age group"])
df[cols] = df[cols].iloc[:,:].replace({",":""}, regex=True).astype(int)
df

,Geography,Age group,2010,2011,2012,2013,2014,2015,2016
0,"St. John's, Newfoundland and Labrador",All ages,1439,1429,1484,1507,1546,1586,1625
1,"Halifax, Nova Scotia",All ages,2842,2727,2883,3007,3071,3136,3226
2,"Moncton, New Brunswick",All ages,999,960,1017,1045,1071,1096,1128
3,"Saint John, New Brunswick",All ages,1104,1116,1050,1105,1134,1161,1194
4,"Saguenay, Quebec",All ages,1238,1290,1420,1391,1519,1372,1394
5,"Quebec, Quebec",All ages,5520,5565,5769,5765,6050,5829,6154
6,"Sherbrooke, Quebec",All ages,1547,1515,1538,1608,1745,1555,1700
7,"Trois-Rivieres, Quebec",All ages,1435,1313,1426,1391,1546,1556,1563
8,"Montreal, Quebec",All ages,26888,26081,27279,26760,28472,27843,28353
9,"Ottawa-Gatineau, Ontario/Quebec",All ages,7388,7355,7907,7824,8148,8277,8648
10,"Kingston, Ontario",All ages,1353,1368,1440,1396,1446,1495,1547
11,"Peterborough, Ontario",All ages,1140,1155,1163,1248,1292,1337,1384
12,"Oshawa, Ontario",All ages,2140,2249,2334,2456,2543,2635,2716
13,"Toronto, Ontario",All ages,28905,28727,30359,31520,32628,33756,34927
14,"Hamilton, Ontario",All ages,5503,5760,6049,6284,6510,6725,6945
15,"St. Catharines-Niagara, Ontario",All ages,3810,3785,4043,4064,4202,4350,4500
16,"Kitchener-Cambridge-Waterloo, Ontario",All ages,2889,2998,3192,3329,3434,3558,3682
17,"Brantford, Ontario",All ages,1232,1202,1298,1251,1295,1339,1374
18,"Guelph, Ontario",All ages,988,896,1026,1021,1045,1077,1128
19,"London, Ontario",All ages,3473,3630,3708,3946,4086,4225,4369
20,"Windsor, Ontario",All ages,2397,2449,2521,2569,2658,2750,2845
21,"Barrie, Ontario",All ages,1226,1176,1297,1344,1393,1426,1482
22,"Greater Sudbury, Ontario",All ages,1442,1402,1499,1585,1642,1698,1757
23,"Thunder Bay, Ontario",All ages,1268,1239,1234,1254,1296,1343,1388
24,"Winnipeg, Manitoba",All ages,5993,5885,6065,6005,6115,6231,6350
25,"Regina, Saskatchewan",All ages,1692,1651,1743,1738,1754,1780,1801
26,"Saskatoon, Saskatchewan",All ages,1837,1757,1846,1981,2006,2028,2057
27,"Calgary, Alberta",All ages,5537,5634,6131,6226,6449,6655,6875
28,"Edmonton, Alberta",All ages,6530,6739,7246,7628,7905,8173,8422
29,"Kelowna, British Columbia",All ages,1575,1593,1589,1604,1683,1717,1846
30,"Abbotsford-Mission, British Columbia",All ages,1162,1203,1238,1173,1228,1252,1348
31,"Vancouver, British Columbia",All ages,13553,13811,13978,14254,14943,15290,16471
32,"Victoria, British Columbia",All ages,3202,3170,3138,3091,3236,3300,3549

In [5]:
df.dtypes

Geography    object
Age group    object
2010          int32
2011          int32
2012          int32
2013          int32
2014          int32
2015          int32
2016          int32
dtype: object

# Each Year dataframe

In [6]:
# Creating df for each year
# sort cities alphabatically
df_2010 = df[["Geography", "Age group", "2010"]]
df_2010 = df_2010.set_index(["Geography", "Age group"])
df_2010 = df_2010.sort_index(level=["Geography"])

df_2011 = df[["Geography", "Age group", "2011"]]
df_2011 = df_2011.set_index(["Geography", "Age group"])
df_2011 = df_2011.sort_index(level=["Geography"])

df_2012 = df[["Geography", "Age group", "2012"]]
df_2012 = df_2012.set_index(["Geography", "Age group"])
df_2012 = df_2012.sort_index(level=["Geography"])

df_2013 = df[["Geography", "Age group", "2013"]]
df_2013 = df_2013.set_index(["Geography", "Age group"])
df_2013 = df_2013.sort_index(level=["Geography"])

df_2014 = df[["Geography", "Age group", "2014"]]
df_2014 = df_2014.set_index(["Geography", "Age group"])
df_2014 = df_2014.sort_index(level=["Geography"])

df_2015 = df[["Geography", "Age group", "2015"]]
df_2015 = df_2015.set_index(["Geography", "Age group"])
df_2015 = df_2015.sort_index(level=["Geography"])

df_2016 = df[["Geography", "Age group", "2016"]]
df_2016 = df_2016.set_index(["Geography", "Age group"])
df_2016 = df_2016.sort_index(level=["Geography"])

# 2016

In [7]:
# add population for 2016
df_2016

                                                  2016
Geography                             Age group
Abbotsford-Mission, British Columbia  All ages    1348
Barrie, Ontario                       All ages    1482
Brantford, Ontario                    All ages    1374
Calgary, Alberta                      All ages    6875
Edmonton, Alberta                     All ages    8422
Greater Sudbury, Ontario              All ages    1757
Guelph, Ontario                       All ages    1128
Halifax, Nova Scotia                  All ages    3226
Hamilton, Ontario                     All ages    6945
Kelowna, British Columbia             All ages    1846
Kingston, Ontario                     All ages    1547
Kitchener-Cambridge-Waterloo, Ontario All ages    3682
London, Ontario                       All ages    4369
Moncton, New Brunswick                All ages    1128
Montreal, Quebec                      All ages   28353
Oshawa, Ontario                       All ages    2716
Ottawa-Gatineau, Ontario/Quebec       All ages    8648
Peterborough, Ontario                 All ages    1384
Quebec, Quebec                        All ages    6154
Regina, Saskatchewan                  All ages    1801
Saguenay, Quebec                      All ages    1394
Saint John, New Brunswick             All ages    1194
Saskatoon, Saskatchewan               All ages    2057
Sherbrooke, Quebec                    All ages    1700
St. Catharines-Niagara, Ontario       All ages    4500
St. John's, Newfoundland and Labrador All ages    1625
Thunder Bay, Ontario                  All ages    1388
Toronto, Ontario                      All ages   34927
Trois-Rivieres, Quebec                All ages    1563
Vancouver, British Columbia           All ages   16471
Victoria, British Columbia            All ages    3549
Windsor, Ontario                      All ages    2845
Winnipeg, Manitoba                    All ages    6350

# Combined years dataframe

In [8]:
# set_index = set dataframe index using existing columns
# Create multi-index where Geo is 1st index and Age group is 2nd index
df_new = df.set_index(["Geography", "Age group"])
df_new = df_new.sort_index(level="Geography")
df_new

,,2010,2011,2012,2013,2014,2015,2016
Geography,Age group,,,,,,,
"Abbotsford-Mission, British Columbia",All ages,1162,1203,1238,1173,1228,1252,1348
"Barrie, Ontario",All ages,1226,1176,1297,1344,1393,1426,1482
"Brantford, Ontario",All ages,1232,1202,1298,1251,1295,1339,1374
"Calgary, Alberta",All ages,5537,5634,6131,6226,6449,6655,6875
"Edmonton, Alberta",All ages,6530,6739,7246,7628,7905,8173,8422
"Greater Sudbury, Ontario",All ages,1442,1402,1499,1585,1642,1698,1757
"Guelph, Ontario",All ages,988,896,1026,1021,1045,1077,1128
"Halifax, Nova Scotia",All ages,2842,2727,2883,3007,3071,3136,3226
"Hamilton, Ontario",All ages,5503,5760,6049,6284,6510,6725,6945
"Kelowna, British Columbia",All ages,1575,1593,1589,1604,1683,1717,1846
"Kingston, Ontario",All ages,1353,1368,1440,1396,1446,1495,1547
"Kitchener-Cambridge-Waterloo, Ontario",All ages,2889,2998,3192,3329,3434,3558,3682
"London, Ontario",All ages,3473,3630,3708,3946,4086,4225,4369
"Moncton, New Brunswick",All ages,999,960,1017,1045,1071,1096,1128
"Montreal, Quebec",All ages,26888,26081,27279,26760,28472,27843,28353
"Oshawa, Ontario",All ages,2140,2249,2334,2456,2543,2635,2716
"Ottawa-Gatineau, Ontario/Quebec",All ages,7388,7355,7907,7824,8148,8277,8648
"Peterborough, Ontario",All ages,1140,1155,1163,1248,1292,1337,1384
"Quebec, Quebec",All ages,5520,5565,5769,5765,6050,5829,6154
"Regina, Saskatchewan",All ages,1692,1651,1743,1738,1754,1780,1801
"Saguenay, Quebec",All ages,1238,1290,1420,1391,1519,1372,1394
"Saint John, New Brunswick",All ages,1104,1116,1050,1105,1134,1161,1194
"Saskatoon, Saskatchewan",All ages,1837,1757,1846,1981,2006,2028,2057
"Sherbrooke, Quebec",All ages,1547,1515,1538,1608,1745,1555,1700
"St. Catharines-Niagara, Ontario",All ages,3810,3785,4043,4064,4202,4350,4500
"St. John's, Newfoundland and Labrador",All ages,1439,1429,1484,1507,1546,1586,1625
"Thunder Bay, Ontario",All ages,1268,1239,1234,1254,1296,1343,1388
"Toronto, Ontario",All ages,28905,28727,30359,31520,32628,33756,34927
"Trois-Rivieres, Quebec",All ages,1435,1313,1426,1391,1546,1556,1563
"Vancouver, British Columbia",All ages,13553,13811,13978,14254,14943,15290,16471
"Victoria, British Columbia",All ages,3202,3170,3138,3091,3236,3300,3549
"Windsor, Ontario",All ages,2397,2449,2521,2569,2658,2750,2845
"Winnipeg, Manitoba",All ages,5993,5885,6065,6005,6115,6231,6350

In [9]:
# Creating csv file for each year
# replace / to \ if mac user.
df_2010.to_csv("datas/new_mortality/2010 mortality.csv")
df_2011.to_csv("datas/new_mortality/2011 mortality.csv")
df_2012.to_csv("datas/new_mortality/2012 mortality.csv")
df_2013.to_csv("datas/new_mortality/2013 mortality.csv")
df_2014.to_csv("datas/new_mortality/2014 mortality.csv")
df_2015.to_csv("datas/new_mortality/2015 mortality.csv")
df_2016.to_csv("datas/new_mortality/2016 mortality.csv")

# # for all years
df_new.to_csv("datas/new_mortality/Combined mortality.csv")