In [1]:
import os, csv
import pandas as pd
import numpy as np

In [2]:
file_path = os.path.join("datas", "new_mortality", "mortality_data.csv")

df = pd.read_csv(file_path)

In [3]:
# Fill NaN with corresponding city
df["Geography"] = df["Geography"].ffill(axis=0)

# Each Year dataframe

In [5]:
# Creating df for each year
df_2010 = df[["Geography", "Age group", "2010"]]
df_2010 = df_2010.set_index(["Geography", "Age group"])

df_2011 = df[["Geography", "Age group", "2011"]]
df_2011 = df_2011.set_index(["Geography", "Age group"])

df_2012 = df[["Geography", "Age group", "2012"]]
df_2012 = df_2012.set_index(["Geography", "Age group"])

df_2013 = df[["Geography", "Age group", "2013"]]
df_2013 = df_2013.set_index(["Geography", "Age group"])

df_2014 = df[["Geography", "Age group", "2014"]]
df_2014 = df_2014.set_index(["Geography", "Age group"])

df_2015 = df[["Geography", "Age group", "2015"]]
df_2015 = df_2015.set_index(["Geography", "Age group"])

df_2016 = df[["Geography", "Age group", "2016"]]
df_2016 = df_2016.set_index(["Geography", "Age group"])

# Combined years dataframe

In [6]:
# set_index = set dataframe index using existing columns
# Create multi-index where Geo is 1st index and Age group is 2nd index
df_new = df.set_index(["Geography", "Age group"])
df_new

                                                          2010   2011   2012  \
Geography                             Age group
St. John's, Newfoundland and Labrador All ages           1,439  1,429  1,484
                                      -1 year 7             12     11     11
                                      0 to 4 years           2      3      0
                                      5 to 9 years           0      0      0
                                      10 to 14 years         0      3      0
                                      15 to 19 years         3      5      6
                                      20 to 24 years         5      7      5
                                      25 to 29 years         2      7      3
                                      30 to 34 years         6      6     15
                                      35 to 39 years        13     15      9
                                      40 to 44 years        26     16     19
                                      45 to 49 years        33     40     31
                                      50 to 54 years        48     52     51
                                      55 to 59 years        85     93     91
                                      60 to 64 years        98     92     89
                                      65 to 69 years       111    130    137
                                      70 to 74 years       149    144    146
                                      75 to 79 years       173    165    177
                                      80 to 84 years       225    223    233
                                      85 to 89 years       244    210    227
                                      90 years and over    204    207    234
Halifax, Nova Scotia                  All ages           2,842  2,727  2,883
                                      -1 year 7             16     20     20
                                      0 to 4 years          11      3      3
                                      5 to 9 years           1      1      2
                                      10 to 14 years         1      2      0
                                      15 to 19 years        15     14      7
                                      20 to 24 years        17     11     16
                                      25 to 29 years        10     13     13
                                      30 to 34 years        20     14     20
...                                                        ...    ...    ...
Vancouver, British Columbia           50 to 54 years       454    492    456
                                      55 to 59 years       628    636    684
                                      60 to 64 years       843    807    847
                                      65 to 69 years       918    886  1,047
                                      70 to 74 years     1,108  1,202  1,092
                                      75 to 79 years     1,590  1,547  1,572
                                      80 to 84 years     2,062  2,157  2,080
                                      85 to 89 years     2,412  2,363  2,420
                                      90 years and over  2,528  2,706  2,778
Victoria, British Columbia            All ages           3,202  3,170  3,138
                                      -1 year 7             11     11      8
                                      0 to 4 years           1      0      2
                                      5 to 9 years           1      1      1
                                      10 to 14 years         1      1      1
                                      15 to 19 years         7      5      4
                                      20 to 24 years        15      9     13
                                      25 to 29 years        14     11     15
                                      30 to 34 years        15     13      8
                                      35 to 39 years        13     21     15
                                      40 to 44 years        26     34     29
                                      45 to 49 years        58     56     43
                                      50 to 54 years        96     96     77
                                      55 to 59 years       142    129    131
                                      60 to 64 years       152    166    172
                                      65 to 69 years       159    184    202
                                      70 to 74 years       192    224    218
                                      75 to 79 years       364    309    288
                                      80 to 84 years       488    495    465
                                      85 to 89 years       709    645    616
                                      90 years and over    738    760    830

                                                          2013   2014   2015  \
Geography                             Age group
St. John's, Newfoundland and Labrador All ages           1,507  1,546  1,586
                                      -1 year 7             14     14     14
                                      0 to 4 years           2      1      2
                                      5 to 9 years           2      2      2
                                      10 to 14 years         3      2      1
                                      15 to 19 years         4      4      4
                                      20 to 24 years         6      7      6
                                      25 to 29 years         9      8      8
                                      30 to 34 years        15     16     16
                                      35 to 39 years         6      6      5
                                      40 to 44 years        14     14     14
                                      45 to 49 years        39     39     39
                                      50 to 54 years        47     47     48
                                      55 to 59 years        88     88     88
                                      60 to 64 years        99    100    102
                                      65 to 69 years       154    163    171
                                      70 to 74 years       146    155    162
                                      75 to 79 years       187    193    200
                                      80 to 84 years       222    229    233
                                      85 to 89 years       219    224    234
                                      90 years and over    231    234    237
Halifax, Nova Scotia                  All ages           3,007  3,071  3,136
                                      -1 year 7             12     12     12
                                      0 to 4 years           8      8      8
                                      5 to 9 years           4      5      5
                                      10 to 14 years         6      6      6
                                      15 to 19 years        12     12     12
                                      20 to 24 years        12     11     12
                                      25 to 29 years        11     11     11
                                      30 to 34 years        15     14     17
...                                                        ...    ...    ...
Vancouver, British Columbia           50 to 54 years       459    469    455
                                      55 to 59 years       710    726    729
                                      60 to 64 years       842    869    880
                                      65 to 69 years     1,079  1,143  1,195
                                      70 to 74 years     1,140  1,213  1,252
                                      75 to 79 years     1,520  1,582  1,619
                                      80 to 84 years     2,201  2,266  2,279
                                      85 to 89 years     2,462  2,561  2,607
                                      90 years and over  2,856  3,114  3,295
Victoria, British Columbia            All ages           3,091  3,236  3,300
                                      -1 year 7             12     12     11
                                      0 to 4 years           2      2      2
                                      5 to 9 years           1      1      1
                                      10 to 14 years         3      3      3
                                      15 to 19 years         8      8      7
                                      20 to 24 years        10     10     10
                                      25 to 29 years        10     11     11
                                      30 to 34 years        17     16     17
                                      35 to 39 years        17     18     17
                                      40 to 44 years        22     22     20
                                      45 to 49 years        48     47     45
                                      50 to 54 years        79     81     79
                                      55 to 59 years       130    134    134
                                      60 to 64 years       170    175    175
                                      65 to 69 years       193    204    213
                                      70 to 74 years       229    244    248
                                      75 to 79 years       308    319    325
                                      80 to 84 years       445    459    460
                                      85 to 89 years       590    614    628
                                      90 years and over    797    856    894

                                                          2016
Geography                             Age group
St. John's, Newfoundland and Labrador All ages           1,625
                                      -1 year 7             14
                                      0 to 4 years           1
                                      5 to 9 years           1
                                      10 to 14 years         1
                                      15 to 19 years         4
                                      20 to 24 years         5
                                      25 to 29 years         9
                                      30 to 34 years        15
                                      35 to 39 years         5
                                      40 to 44 years        13
                                      45 to 49 years        39
                                      50 to 54 years        47
                                      55 to 59 years        88
                                      60 to 64 years       101
                                      65 to 69 years       174
                                      70 to 74 years       179
                                      75 to 79 years       209
                                      80 to 84 years       240
                                      85 to 89 years       237
                                      90 years and over    243
Halifax, Nova Scotia                  All ages           3,226
                                      -1 year 7             12
                                      0 to 4 years           8
                                      5 to 9 years           5
                                      10 to 14 years         6
                                      15 to 19 years        12
                                      20 to 24 years        11
                                      25 to 29 years        11
                                      30 to 34 years        16
...                                                        ...
Vancouver, British Columbia           50 to 54 years       469
                                      55 to 59 years       768
                                      60 to 64 years       943
                                      65 to 69 years     1,303
                                      70 to 74 years     1,365
                                      75 to 79 years     1,735
                                      80 to 84 years     2,410
                                      85 to 89 years     2,815
                                      90 years and over  3,637
Victoria, British Columbia            All ages           3,549
                                      -1 year 7             12
                                      0 to 4 years           2
                                      5 to 9 years           1
                                      10 to 14 years         3
                                      15 to 19 years         7
                                      20 to 24 years        10
                                      25 to 29 years        11
                                      30 to 34 years        18
                                      35 to 39 years        19
                                      40 to 44 years        21
                                      45 to 49 years        49
                                      50 to 54 years        78
                                      55 to 59 years       143
                                      60 to 64 years       185
                                      65 to 69 years       228
                                      70 to 74 years       273
                                      75 to 79 years       349
                                      80 to 84 years       484
                                      85 to 89 years       677
                                      90 years and over    979

[693 rows x 7 columns]

In [11]:
# Creating csv file for each year
df_2010.to_csv("2010 mortality.csv")
df_2011.to_csv("2011 mortality.csv")
df_2012.to_csv("2012 mortality.csv")
df_2013.to_csv("2013 mortality.csv")
df_2014.to_csv("2014 mortality.csv")
df_2015.to_csv("2015 mortality.csv")
df_2016.to_csv("2016 mortality.csv")

# for all years
df_new.to_csv("Combined mortality.csv")